export const GET_OPENED_MONSTER = "GET_OPENED_MONSTER";
export const SAVE_OPENED_MONSTER = "SAVE_OPENED_MONSTER";
export const MONSTER_CHANGED = "MONSTER_CHANGED";
export const GET_MONSTERS = "GET_MONSTERS";
export const GET_COMBATANTS = "GET_COMBATANTS";
export const GET_SELECTED_TAB = "GET_SELECTED_TAB";